# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 472e9c4556bb9b52ecc9329ad7ac9fbcb6e822505f95193c2e5d46a37397033b751c5b7ae84dd46c446140431d86d214dadf2b7783f897ccad416bfa75371e3e

test:
  secret_key_base: 2ba06618146498def9c0166a950696fde47e68bb4385a5a11dc19ba731e3a35dfc2c8055d4ffdb22e1dfbc228deb190b37465854a65248e75a5d6eeb59fe5e95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
